### ISSUE TITLE
NPE in ActorSystem.close on calling api.switchToDc

### ISSUE THREAD

**Issue by ghost** [telegram-s/telegram-actors#1]
Hi,

When I try calling api.switchToDc I get a NullPointerException in ActorSystem.
I didn't have this before.

```
Exception in thread "main" java.lang.NullPointerException
at org.telegram.actors.ActorSystem.close(ActorSystem.java:97)
at org.telegram.mtproto.MTProto.close(MTProto.java:221)
at org.telegram.api.engine.TelegramApi.switchToDc(TelegramApi.java:161)
at TelegramApplication.authSendCode(TelegramApplication.java:59)
at TelegramApplication.updateDatacenters(TelegramApplication.java:43)
at TelegramService.run(TelegramService.java:9)
at TelegramService.main(TelegramService.java:4)
```

**Comment by ashokcoolguys** [comment]
Have you fixed this issue..
